### ISSUE TITLE
Project is still Hello World

### ISSUE THREAD

**Issue by tazmancoder** [myawesomehub/CO-Voice#2]
When do you plan on updating this repo? It would be nice to see the complete code.

**Comment by thatswiftguy** [comment]
Let me do it right now !

**Comment by tazmancoder** [comment]
Thank you, I appreciate that.


-Mark/*

Mark J Perryman
Apple Product Enthusiast
(435) 882-1008

**Comment by thatswiftguy** [comment]
See, I had added a file... however thats not a right way to do these,, there is something wrong with repository... try to access the code files..
